filename: "./2meter.pcd"
tag_family: "tag36h11"
marker_size: 0.164
tolerance: 1.0
ratio_threshold: 1.1
buffer: 3.0
intensity_threshold : 8000
EuclideanTolerance: 0.01
ang_resolution: 0.1
binary_threshold: 70
norm_radius: 0.01 #0.005,0.019
gradient_radius: 0.01

