filename: "./merged.pcd"
tag_family: "tag36h11"
marker_size: 0.2
tolerance: 0.1
ratio_threshold: 1.5
buffer: 10.0
intensity_threshold : 1000
EuclideanTolerance: 0.03
ang_resolution: 0.1
binary_threshold: 70
norm_radius: 0.005 #0.005,0.019
gradient_radius: 0.005

